USE DATABASE SNOWPARK_DB;

CREATE SCHEMA IF NOT EXISTS STAGGING;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS TRANSFORMED;
CREATE SCHEMA IF NOT EXISTS CURATED;

USE SCHEMA STAGGING;

-- ---------- INDIA ----------
CREATE TABLE IF NOT EXISTS INDIA_ORDERS (
    ORDER_ID STRING,
    ORDER_DATE DATE,
    CUSTOMER_NAME STRING,
    STATE STRING,
    CITY STRING
);

CREATE TABLE IF NOT EXISTS INDIA_ORDER_DETAILS (
    ORDER_ID STRING,
    AMOUNT STRING,
    PROFIT STRING,
    QUANTITY STRING,
    CATEGORY STRING,
    SUB_CATEGORY STRING
);

CREATE TABLE IF NOT EXISTS INDIA_SALES_TARGETS (
    ORDER_MONTH STRING,
    CATEGORY STRING,
    TARGET STRING
);

-- ---------- USA ----------
CREATE TABLE IF NOT EXISTS USA_SALES_ORDER_CP (
    "Row ID" NUMBER,
    "Order ID" STRING,
    "Order Date" DATE,
    "Ship Date" DATE,
    "Ship Mode" STRING,
    "Customer ID" STRING,
    "Country" STRING,
    "City" STRING,
    "State" STRING,
    "Postal Code" STRING,
    "Region" STRING,
    "Product ID" STRING,
    "Category" STRING,
    "Sub-Category" STRING,
    "Product Name" STRING,
    "Sales" STRING,
    "Quantity" STRING,
    "Discount" STRING,
    "Profit" STRING
);

-- ---------- UK ----------
CREATE TABLE IF NOT EXISTS UK_SALES_ORDER_CP (
    INVOICE_NO STRING,
    STOCK_CODE STRING,
    DESCRIPTION STRING,
    QUANTITY STRING,
    INVOICE_DATE STRING,
    UNIT_PRICE STRING,
    CUSTOMER_ID STRING,
    COUNTRY STRING
);

-- --------- STAGE ----------
CREATE STAGE IF NOT EXISTS SNOWPARK_STAGE
STORAGE_INTEGRATION = SNOWPARK_INT
URL = 's3://global-sales-snowpark-bucket/data/';

LIST @SNOWPARK_STAGE;
